name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Instalar dependências
        run: npm ci

      - name: Build da aplicação
        run: npm run build

      - name: Build da imagem Docker
        run: docker build -t devops-app .